questions
MaKu-kodilla/ES6_practice pull request #4
Opened 2018-05-22 18:58 UTC by MaKu-kodilla

Hej,

możesz na to zerknąć?

Zastanawiam się jak załadować style.css skoro nie mogę skorzystać z opcji import.

2018-05-24 19:26 UTC, michal-bootcamp commented
style zwyczajnie przez html tak, jak masz teraz :)

dodaj do projektu `babel-preset-react`

2018-05-24 21:16 UTC, MaKu-kodilla commented
dodałem babel'a, w consoli wyrzuca mi taki błąd 
https://scr.hu/Dq8wyA - jakiś problem z tym .bindem jest?

2018-05-28 01:48 UTC, michal-bootcamp commented
zastanow sie co wlasciwie ma robic funkcja `handleStartClick` i czy jest ona gdzies zdefiniowana?

2018-05-28 20:35 UTC, MaKu-kodilla commented
ok, ten problem rozwiązany :) rzeczywiście, żadna z tych funkcji nie była zdefiniowana...
Została jedna rzecz: https://scr.hu/2lByK9
Jakaś podpowiedź? 
Nie mogę tego rozgryźć :/

2018-05-28 23:46 UTC, michal-bootcamp requested changes

2018-05-28 23:46 UTC, michal-bootcamp commented on Zadanie 15.4 Przekształcenie stopera na składnię ES6/script.js
> +        this.times.miliseconds +=1;
akurat dla tego przypadku devtoolsy firefoxa podaja ten komunikat w troche innych slowach - moze bardziej zrozumialych.
Moja podpowiedz: znajdz skad bierzesz wartosc `this.times.miliseconds` i sprawdz, czy na pewno tak sie do niej dostaniesz

2018-07-06 15:12 UTC, merged